dockerfile: |-
  RUN apk add --no-cache build-base yaml-dev git
  RUN gem update --system
  RUN gem install bundler gem_hadar

script: &script |-
  echo -e "\e[1m"
  ruby -v
  bundle update
  bundle install --jobs=$(getconf _NPROCESSORS_ONLN)
  bundle
  echo -e "\e[0m"
  rake spec

images:
  ruby:3.4-alpine: *script
  ruby:3.3-alpine: *script
  ruby:3.2-alpine: *script
  ruby:3.1-alpine: *script
